### ISSUE TITLE
Does not work with latest bdk-flutter

### ISSUE THREAD

**Issue by MrUnfunny** [LtbLightning/bdk-flutter-app#2]
Hey @BitcoinZavior,
This app doesn't seem to work with main branch of bdk-flutter. Some APIs have been changed but it seems to work fine with 
```yaml
  bdk_flutter:
    git:
      url: https://github.com/LtbLightning/bdk-flutter
      ref: 116e4c095cb1eac6cbfd00328d0c9e2a47ba6735
```

With this version, it works fine on android but I'm unable to run it on iOS. Is there any plan for updating the app to work with latest version of bdk-flutter?
